// SESSION
export const SESSION_REQUEST = 'SESSION_REQUEST';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SESSION_FAILURE = 'SESSION_FAILURE';
export const SESSION_DESTROY = 'SESSION_DESTROY';
export const UNAUTHENTICATED_REQUEST = 'UNAUTHENTICATED_REQUEST';

// RESCUERS
export const RESCUERS_REQUEST = 'RESCUERS_REQUEST';
export const RESCUERS_SUCCESS = 'RESCUERS_SUCCESS';
export const RESCUERS_FAILURE = 'RESCUERS_FAILURE';
