// SESSION
export const SESSION_REQUEST = 'SESSION_REQUEST';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SESSION_FAILURE = 'SESSION_FAILURE';
export const SESSION_DESTROY = 'SESSION_DESTROY';
export const UNAUTHENTICATED_REQUEST = 'UNAUTHENTICATED_REQUEST';

// RESCUERS
export const RESCUERS_REQUEST = 'RESCUERS_REQUEST';
export const RESCUERS_SUCCESS = 'RESCUERS_SUCCESS';
export const RESCUERS_FAILURE = 'RESCUERS_FAILURE';

// RESCUERS-DETAIL
export const RESCUERS_DETAIL_REQUEST = 'RESCUERS_DETAIL_REQUEST';
export const RESCUERS_DETAIL_SUCCESS = 'RESCUERS_DETAIL_SUCCESS';
export const RESCUERS_DETAIL_EDIT = 'RESCUERS_DETAIL_EDIT';
export const RESCUERS_DETAIL_SET = 'RESCUERS_DETAIL_SET';
export const RESCUERS_DETAIL_FAILURE = 'RESCUERS_DETAIL_FAILURE';

// AREA
export const AREA_DETAIL_SET = 'AREA_DETAIL_SET';


// ACTION
export const ACTIONS_REQUEST = 'ACTIONS_REQUEST';
export const ACTIONS_SUCCESS = 'ACTIONS_SUCCESS';
export const ACTIONS_FAILURE = 'ACTIONS_FAILURE';

// HISTORY
export const HISTORY_REQUEST = 'HISTORY_REQUEST';
export const HISTORY_SUCCESS = 'HISTORY_SUCCESS';
export const HISTORY_FAILURE = 'HISTORY_FAILURE';

export const RESCUE_FINISH = 'RESCUE_FINISH';

