// SESSION
export const SESSION_REQUEST = 'SESSION_REQUEST';
export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SESSION_FAILURE = 'SESSION_FAILURE';
export const SESSION_DESTROY = 'SESSION_DESTROY';
export const UNAUTHENTICATED_REQUEST = 'UNAUTHENTICATED_REQUEST';

